### ISSUE TITLE
Charts/Aggs on Search Interface

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#1]
https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal
![image](https://user-images.githubusercontent.com/15824252/112682805-01dcc580-8e47-11eb-948d-6ef482879d96.png)

**Comment by rosibaj** [comment]
Feedback April 05, 2021:
- [ ]  Scroll issue with charts now: https://drive.google.com/file/d/1HJXPMb-vn0FGLbqvuwgHWmyGQIuBYeJ3/view

**Comment by caravinci** [comment]
Thanks for the video, @rosibaj. I see now the issue you meant, which I cannot replicate locally in any of my browsers (I'm on a Mac). Will have to run some tests on other devices in order to figure out what the problem may be. 
Of note, in your video, the scrollbar is still there, even as the charts are not (i.e. the issue is there before I've made any changes to the explore page). Rather puzzling. Could be something with the navbar instead.
Shall update here with any conclusions. Moving back to in progress.

**Comment by caravinci** [comment]
Seeing the problem is only evident when the scrollbars are always displayed if available (in contrast with MacOS autohiding scrollbars) and also using a Linux + Firefox setup to confirm, I'm noticing the same issue is presented in the latest DMS-UI release when the screen is lower than approximately 1155px (the specific number could be related to ontological details like screen resolution, etc. so I'll assume a random "minimum width"). The issue seems to be caused by a different implementation of CSS grids, feature used in the main layout container.

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/e044582b-df36-4cdf-a15b-1930f01604f7)

Seeing the cause of the issue, I am working on a universally compatible fix. Good catch, @rosibaj.
I'll be testing my subsequent releases in my linux machine henceforth.

**Comment by caravinci** [comment]
Verified fix works on Mac Chrome, Safari, Firefox, and then on Linux Chrome and Firefox. 🤞

The scrolling issues seem to be mostly resolved, and i've replicated the changes into DMS-UI with PR https://github.com/overture-stack/dms-ui/pull/98.

**Comment by rosibaj** [comment]
@caravinci fix looks great! Imm not able to recreate at all!
