### ISSUE TITLE
Select all for metadata download (FR)

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#153]
A user asked if it would be possible to add a "select all" for metadata columns for download

**Comment by b-f-chan** [comment]
@scottcain we need more details on this:

(1) Are you talking about download from Exploration page, or the Release page, or both?

(2) If you're talking about the Exploration page, when you say "Select All" metadata columns, do you mean all columns from the results table?  If so, I do not understand the requirement, because the TSV already includes all (and actually more than) the columns displayed in the results table.  This is true for the TSV in both the Exploration page and the Releases page.  I'm probably misunderstanding here, but what columns are missing then?  See attached example.

**Comment by b-f-chan** [comment]
@scottcain - Can you please help us answer the above?

**Comment by scottcain** [comment]
Yeah, I am pretty sure that this question came up as a result of both the user and me not being sure how the explorer page works. There is no "selected columns for download" since if a user downloads, they are getting every column/field. The user was confused by the fact that you can change the display to show or hide some columns but the downloads are not affected by those UI choices. This has been alleviated by a subsequent change to the UI to add a hover tooltip to let the user know that the changes in the explorer ui don't apply to downloads. I'm closing this as a result.
