### ISSUE TITLE
Broken connectivity to viral.ai 

### ISSUE THREAD

**Issue by nknox** [cancogen-virus-seq/portal#187]
Prior to the broken fibre issue a couple weeks ago, we were able to query the data portal through viral.ai. Now when trying to query the virusseq data portal through viral.ai, we get the following error:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ga4gh-service-registry.publisher.dnastack.com', port=443): Max retries exceeded with url: /services (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f70c1ab0490>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by mbarkley** [comment]
Hi @nknox, I was linked to this ticket by a colleague of yours. Am I correct in assuming that you encountered this error while using the Python library documented [here](https://docs.viral.ai/analysis/python-library/#installation)?

If that's the case, you are encountering a bug that was only recently exposed by some infrastructure changes made by my team. While there is no _new_ version with a fix, it is possible to _downgrade_ to a version without this issue. You'll want to use the `0.3.5` in your `requirements.txt` or directly with pip (`pip install dnastack-client-library==0.3.5`).

Note that because of some internal dependencies, `0.3.5` may require you to use Python 3.9 or newer.

Hope that helps.

**Comment by scottcain** [comment]
@nknox can you verify that the suggested fix from @mbarkley worked for you? Thanks!

**Comment by nknox** [comment]
It works - thank you!

**Comment by nknox** [comment]
Sorry - may have to reopen this issue. It seems like it's only pulling a subset of the records. I can't grab all records. @mbarkley  can you confirm that nothing else is going on?

**Comment by mbarkley** [comment]
@nknox My apologies, but that older version has a bug that I thought was patched. Our team has just pushed a new release that has fixes for the original problem your reported, and the bug that doesn't fetch all results. It has a slight change in the return type of the query method, but here is code I have successfully run myself that you can try with version `1.0.2`:
```python
# Import the dnastack-client-library library
from dnastack import PublisherClient

# Create the client
collections_url = 'https://viral.ai/api/collections/'
publisher_client = PublisherClient(collections_url=collections_url)

# Query a collection
collection_name = 'ncbi-sra'
query = 'SELECT * FROM publisher_data.ncbi_sra.variants LIMIT 200000'
data = publisher_client.collections.query(collection_name,query)
print(data)

i = 0
for row in data:
  i = i + 1
  print("row " + str(i))
  print(row)
```
