### ISSUE TITLE
Metadata update- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#238]
Hi there @scottcain ,

Could you please update the Isolate name for a QC sample (QC_342812) to hCoV-19/Canada/QC-L00430089001/2022 ?

Thanks,
Chanchal

**Comment by lindaxiang** [comment]
@ChanchalYa @scottcain  , I can change the isolate name to `hCoV-19/Canada/QC-L00430089001/2022`, 
however FYI, 
the "fasta_header_name" will still be "hCoV-19/Canada/QC-L00430089001/2021", because that needs to be the same ID in the fasta file, is that okay for you?

Otherwise if you want to make `isolate` and `fasta_header_name` consistent, we need to remove the sample and its fasta data, and you re-submit the sample metadata and fasta file with modified `isolate` and `fasta_header_name`. 

Please let me know how you want to proceed. Thanks.
Linda

**Comment by ChanchalYa** [comment]
Hi @lindaxiang ,

Thank you for this information. Could you please remove this sample from the portal? I am going to re-submit the modified tsv and fasta files for this particular sample to Nithu for the upload.

Thanks,
Chanchal

**Comment by ChanchalYa** [comment]
Thanks very much @lindaxiang . Nithu has re-submitted the sample.
