### ISSUE TITLE
Metadata updates- QC

### ISSUE THREAD

**Issue by ChanchalYa** [cancogen-virus-seq/portal#240]
Hi there @scottcain ,

Could you please update the "sequencing protocol" for the list of QC samples attached here? Our partners have provided these updates.

Thanks,
Chanchal
[QC_Metadata_updates_20220502.csv](https://github.com/cancogen-virus-seq/portal/files/8603410/QC_Metadata_updates_20220502.csv)
l

**Comment by lindaxiang** [comment]
@scottcain @ChanchalYa The above samples have been updated. To be noted, only 1439 samples got updated because the other 1282 samples already have the same values as what are in the file. 
Here is the log:
[LSPQ-QC.update_sequencing_protocol.log](https://github.com/cancogen-virus-seq/portal/files/8627079/LSPQ-QC.update_sequencing_protocol.log)

**Comment by ChanchalYa** [comment]
Thanks @lindaxiang !
