### ISSUE TITLE
User interface updates

### ISSUE THREAD

**Issue by scottcain** [cancogen-virus-seq/portal#246]
During the call today, we discussed multiple user interface updates that are needed to add new items. These include:

* moving the "CanCOGen" part of the logo down to by the Genome Canada logo (to free up horizontal space near the menu and to deemphasize CanCOGen since it's no longer a funder).
* adding a Tools menu item, which would have on it links to tools hosted at VirusSeq (like explore and CoViZu) as well as link outs to CovidMVP, ViralAI and Doutang.
* Perhaps moving the "meet the team" and "acknowledgements" links to a menu under the "About" item.
* Getting rid of the "Meet the team" blue button under the counts, possibly replacing it with a link to something more useful like a link to CoViZu.

**Comment by b-f-chan** [comment]
Addressing in order, all good ideas:

(1) Moving CanCOGen part of logo is possible, would need some help from @kcullion for re-design
(2) @kcullion can advise on this and suggest a proper layout which we can review with steerco
(3) @kcullion can also advise on this and we'll review with steerco
(4) Can be done, need to decide what replacement is (possibly Tools or Analysis once that's implemented)

All feasible, potentially straightforward, but @scottcain we need to prioritize against all the other more critical items

**Comment by sifavahora** [comment]
In reference with 
`moving the "CanCOGen" part of the logo down to by the Genome Canada logo (to free up horizontal space near the menu and to deemphasize CanCOGen since it's no longer a funder).`

Kim identified that there are lot of references to CanCoGen on the portal. Do we want to remove or make changes around them also. Following is the list of places Cancogen reference exists currently:

1. Introduction Paragraph on the homepage
2. Learn more about CanCOGen button on the bottom right of the homepage
3. https://virusseq-dataportal.ca/releases
4. https://virusseq-dataportal.ca/team
5. https://virusseq-dataportal.ca/acknowledgements
6. https://virusseq-dataportal.ca/policies
7. About CanCoGen link on the footer

**Comment by sifavahora** [comment]
Waiting for mockups to be approved.

**Comment by sifavahora** [comment]
We have the approval for the following 

- moving the "CanCOGen" part of the logo down to by the Genome Canada logo (to free up horizontal space near the menu and to deemphasize CanCOGen since it's no longer a funder).
- adding a Tools menu item, which would have on it links to tools hosted at VirusSeq (like explore and CoViZu) as well as link outs to CovidMVP, ViralAI and Doutang.
- Perhaps moving the "meet the team" and "acknowledgements" links to a menu under the "About" item.

Mockup links are: 
https://projects.invisionapp.com/share/4W10CB0B6YJE#/screens/468031370_02-Homepage-Tools_Dropdown
https://projects.invisionapp.com/share/4W10CB0B6YJE#/screens/468031371_03-Homepage-About_Dropdown

The links to the analysis tools are : 

1. Covizu - as exisiting Visualize Genomes link
2. CovidMVP - https://covidmvp.cidgoh.ca/
3. ViralAI - https://viral.ai/collections/virusseq/overview
4. CoVarrNet-Duotang - Coming soon

**Comment by kcullion** [comment]
@caravinci 
To answer your questions:
- you can export the logo from here: https://zpl.io/Pq53ANm (note, I don't have an svg of these logos so they are just pngs
- yes, I think just clicking on the logo will be going to the homepage. When the site launched there wasn't many sections so we just made the first link the about/homepage. But now it's confusing to have a link in the dropdown link to the homepage - so let's just leave the logo as the standard homepage link.
- great! I think there's a dropdown implemented already for a logged in user, so you can make it consistent with that

**Comment by caravinci** [comment]
Thanks @kcullion!

**Comment by sifavahora** [comment]
The link to Duotang is https://covarr-net.github.io/duotang/duotang.html

**Comment by sifavahora** [comment]
We want to change the blue buttons under the count: 

1. Replace the `Meet the Team` button with `Download the Data` this button redirects to `Data Releases` Page
2. Remove/hide the `Acknowledgements` button. (Going forward we want a button `Analyze the Data` in its place.)

**Comment by sifavahora** [comment]
![image](https://user-images.githubusercontent.com/30519419/180806989-199ad94c-d8d9-4aab-b076-67cb3bd09a9f.png)

We want to change the sentence to "The goal of the CanCOGeN VirusSeq project `was `to sequence up to 150,000 viral......"

**Comment by sifavahora** [comment]
For Reference: this covers https://github.com/cancogen-virus-seq/portal/issues/159
