### ISSUE TITLE
Fix Registration Flows 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/portal#25]
- [x]  Connect the Registration button.  For testing, this whole flow should be correct: 
 https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal#CanCoGenVirusSeqDataPortal-3.0StudyandUserRegistration 
- [x] When a user logs in, and does not have permissions, the submission dashboard should show this no permission state (ie. has no scopes in JWT).
dashboard: https://zpl.io/29mPXBp
profile: https://zpl.io/bAR4NPo

**Comment by caravinci** [comment]
Made all the style changes (assumed scope), the access token field displays the current one and allows copying it.
However, since I still have to figure out how to generate a ones I've removed that button for now, yet will implement that feature as soon as clear from other higher priorities (along with refresh tokens).

**Comment by rosibaj** [comment]
@caravinci i assume you mean regenerate?  This should definitely work now! and looks great so i will close this ticket.

**Comment by caravinci** [comment]
Yeah, I guess in this use case, a better word for generating a new token would be to "regenerate" it :+1:
