### ISSUE TITLE
Samples not Processing while uploads

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/portal#258]
Hi @scottcain, currently doing a bulk upload from BC (28K) and after 4 sets of upload (1034 each set) the data portal is not processing the samples they are shown as "QUEUED". I have included the data submission ID and snap shots. Thanks!

Data Submission: 86f10e77-70ec-4168-bff8-dfe93c904c51
Data Submission: 828bccae-9315-45ec-bc4a-5d95513fab1c
Data Submission: 6dab75e4-fdca-4bef-a0a4-d1e6f2ee4f89
![image](https://user-images.githubusercontent.com/85367999/171942983-a3d88a45-5f09-4d3d-b9d4-8201ba52f864.png)
![image](https://user-images.githubusercontent.com/85367999/171943008-cdf00730-06e4-464b-8e4a-a4579f50c5f6.png)
![image](https://user-images.githubusercontent.com/85367999/171943055-d90b7845-df85-4ec6-a71e-3e23df0ec94d.png)

**Comment by scottcain** [comment]
Hi @nithujohn ,

I'm going to be out of the office for most of this week (I might be checking email in the evening but I won't guarantee it!). I've asked one of our developers to take a look on Monday. I forgot to ask you about letting us know when you get a big batch that you're going to load so we can watch our system in real time to see what it's doing.  Maybe next time!

**Comment by nithujohn** [comment]
thanks @scottcain let me know if I can continue with the uploads and do I have to re- upload the three sets queued.

**Comment by joneubank** [comment]
We investigated the available logs and are not able to see what stopped the uploads and put them into the Queued state... It looks however like when this happens a restart of Muse should clear out the queue and then we can re-upload the samples.

It would if next time this happens (if it happens again) we can quickly check for what errors are causing this state. For now, I would monitor for this behaviour to see how frequently it occurs.

**Comment by nithujohn** [comment]
@joneubank I am currently uploading the samples but one of the set Queued again when I re- uploaded. After an hour I have re- strated the upload and it worked. I am have included the data submission ID below. Thanks!
4ea964fa-19f0-4606-bd7e-15d0dde651f5

**Comment by nithujohn** [comment]
After uploading 6 sets the same issue has been seen!

Data Submission: e76c6ff6-a059-4c97-8107-13d4b9efe5e2
![image](https://user-images.githubusercontent.com/85367999/172690148-7e92b485-af43-4265-93b8-9028061d1e9b.png)

**Comment by joneubank** [comment]
@nithujohn thanks for letting us know, we are investigating right now

**Comment by nithujohn** [comment]
Looks like after 4 or 6 sets the data portal shows similar issue. 

Data Submission: 28929c3a-fa43-4f00-b9d4-373ffd27f8b6
![image](https://user-images.githubusercontent.com/85367999/172724149-c3266ae4-39ab-4815-8762-b298602de556.png)

**Comment by b-f-chan** [comment]
Hi @nithujohn, as mentioned in the e-mail I sent today introducing Sifa Vahora (@sifavahora), she is our new VirusSeq Business Analyst and will help triage and communicate with you on such issues moving forward.

For this particular ticket, we do want to ask if you are able to continue working with this limitation while we try to determine and implement the correct fix.

As noted by @UmmulkiramR above, your batches are actually going through successfully on the backend, but due to the overflow issue, the UI itself is not showing them as successful.

We will need some time to determine this fix while balancing some other prod issues/priorities. So if you can live with this a little longer that would be appreciated.  What we can do, is after you process your batches, or a few batches, you can check in with us and we can confirm it successfully made it into the backend (even though the UI may show stuck in queue).  We can work this way temporarily until we get the fix done.

Please let us know if this works for you or if you have other suggestion - Thank you!

(@sifavahora @UmmulkiramR please correct me if you have a better suggestion as well)

**Comment by UmmulkiramR** [comment]
@b-f-chan @nithujohn, I did look up for the submission ids in the screenshots attached here and I noticed they have not gone through as they show QUEUED in the tables. However, the update I made above is also a problem which was earlier thought to be the same as what @nithujohn is facing. But this new finding shows the two are different.  

For this issue, I can see from the records in the table that the submissions do eventually go through successfully after retrying. 
@nithujohn Please confirm if this is the case.

**Comment by nithujohn** [comment]
@UmmulkiramR most of the sets when I re-tried had gone through successfully but two of the sets was not successful at the second try and I had to re- upload it a third time to be successful. I have included the submission IDs below for second unsuccessful submissions. 

Data Submission: 4ea964fa-19f0-4606-bd7e-15d0dde651f5
Data Submission: bc1b8636-e9a7-4e18-8e1b-4d9ae136b51b

**Comment by UmmulkiramR** [comment]
@nithujohn Thanks. I'll have a look into them.

**Comment by nithujohn** [comment]
@sifavahora @UmmulkiramR I tried to upload 1986 samples from BC and the samples are not processing at my end similar issue
Data Submission: db2adeac-a0ba-4384-be15-6fc08544ad51


![image](https://user-images.githubusercontent.com/85367999/181076748-2bbca369-314a-456f-83af-f324dd0b0b76.png)

**Comment by sifavahora** [comment]
While monitoring upload logs we found the exception same as https://github.com/cancogen-virus-seq/muse/issues/86

**Comment by sifavahora** [comment]
Updating Song and Score and making resource allocation changes on  Muse Pod seems to have solve the issue.
