### ISSUE TITLE
Setup the prerequisites for testing multiple tags for properties

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#296]
1. Do we need to change anything in the templates or harmonizer?
2. Have received a sample tsv with multiple tags for anatomical part, need to create a fasta for the same and confirm the template format. 
3. Do we need anything else to test this? 
[test_multi tags - Copy.tsv.txt](https://github.com/cancogen-virus-seq/portal/files/9190602/test_multi.tags.-.Copy.tsv.txt)

**Comment by edsu7** [comment]
@lindaxiang could you sanity check this? Thanks
[test.fasta.gz](https://github.com/cancogen-virus-seq/portal/files/9193119/test.fasta.gz)

**Comment by lindaxiang** [comment]
@sifavahora @edsu7 The fasta file looks good to me. For metadata file `test_multi tags - Copy.tsv.txt`, here are what I found:
1. `sample collection date` should have the format: "2022-05-01", I am not quite sure if Muse will do the format transformation? If it does, we are all good.
2. `host disease` has value of `COVID- 19`(has a space in between) instead of `COVID-19`, which will report errors for song validation.

**Comment by sifavahora** [comment]
Thanks Linda. I can make that changes.
