### ISSUE TITLE
Hide Host_age Column from the explorer page and remove the column from singularity download.

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#351]
- [ ] Hide the host_age column from explorer page (make sure it is removed from metadata only download also)

- [ ] Remove the host_age column from singularity dataset  (make sure it is removed from singularity tsv downloads too)

**Comment by scottcain** [comment]
About removing it from the singularity dataset: I'm not convinced that they want it removed completely--I think they would like for it to remain in the database, just not be visible to "casual" users. So, remove it from the explorer and remove it from the downloads but keep it in the database so that users who are "allowed" can still get at that data if needed.

**Comment by sifavahora** [comment]
yes by singualrity dataset i mean the download dataset that we give them. the tsv. the data will still be there in the song database

**Comment by leoraba** [comment]
Deployed successfully in Prod on Dec 6, 2022
