### ISSUE TITLE
Metadata Update Request - Purpose of Sequencing (multiple provs)

### ISSUE THREAD

**Issue by KirstenPalmier** [cancogen-virus-seq/portal#404]
Good day @edsu7 ,

Can you please update the `Purpose of sequencing` field for the attached samples?

Thank you,

Kirsten 
[VirusSeq_purpose_of_sequencing_update_20230818.csv](https://github.com/cancogen-virus-seq/portal/files/12381826/VirusSeq_purpose_of_sequencing_update_20230818.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier.

`1710`/`1719` samples' `Purpose of sequencing` of sequencing has been updated.

For the `9`, they were not updated because typo aside the value remained the same
RowInCsv|SampleId|Old Value|New Value
--| -- | -- | --
772 |NS_249187 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
773 |NS_249202 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
774 |NS_249256 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
775 |NS_249258 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
776 |NS_249214 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
777 |NS_249215 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
778 |NS_249218 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
779 |NS_249222 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)
780 |NS_249229 | Baseline surveillance (random sampling) | baseline surveillance (random sampling)


Before:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/612914af-97b8-4254-bfdc-1527a48ba21c)
After:
![image](https://github.com/cancogen-virus-seq/portal/assets/22638361/39971bc0-b28c-46ef-ae1d-71c5fea0090f)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you Edmund!

Kirsten
